on:
  pull_request:
    branches:
       - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: before_script
        run: |
          npm install -g gulp bower codeclimate-test-reporter codacy-coverage
          bower install
      - name: script
        run: gulp
      - name: after_script
        run: |
          codecov < .tmp/js/lcov.info
          codeclimate-test-reporter < ./.tmp/js/lcov.info
          codacy-coverage < .tmp/js/lcov.info
