on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - uses: amancevice/setup-code-climate@5be00b4dc2341fc703265918977bc74d5f453df0
        with:
          cc_test_reporter_id: ${{ secrets.CODECLIMATE_TEST_REPORTER_ID }}
      - name: before_script
        run: |
          npm install -g gulp bower
          npm install
          bower install
      - run: cc-test-reporter before-build
      - name: script
        run: gulp
      - name: after_script
        if: ${{ always() }}
        run: |
          cc-test-reporter format-coverage -t lcov ./.tmp/js/lcov.info
          cc-test-reporter after-build
          
