on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    name: Node ${{ matrix.node }} build
    steps:
      - uses: GitHubSecurityLab/actions-permissions/monitor@v1
        with:
          config: ${{ vars.PERMISSIONS_CONFIG }}
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: before_script
        run: |
          npm install -g gulp bower codeclimate-test-reporter codacy-coverage
          npm install
          bower install
      - name: script
        run: gulp
      - name: after_script
        run: |
          codecov < .tmp/js/lcov.info
          codeclimate-test-reporter < ./.tmp/js/lcov.info
          codacy-coverage < .tmp/js/lcov.info
